// Search Actions
export const SEARCH_REQUEST = "ACTION_SEARCH_REQUEST";
export const SEARCH_REQUEST_SUCCESS = "ACTION_SEQRCH_REQUEST_SUCCESS";
export const SEARCH_REQUEST_ERROR = "ACTION_SEQRCH_REQUEST_ERROR";
